### ISSUE TITLE
聊天过程中Host list出现重复

### ISSUE THREAD

**Issue by JRY-Zheng** [bestony/neshouse#1]
![image](https://user-images.githubusercontent.com/13572492/106846384-bc720680-66e7-11eb-91b1-56fde00e3909.png)
操作：
听众通过邀请链接加入，举手后房主通过申请（此时房主看到提示“通过申请”，听众也看到了），随后将听众mute，就出现了重复现象。

**Comment by bestony** [comment]
已知问题，待解决

**Comment by johnpoint** [comment]
已在 #2 解决
