### ISSUE TITLE
alert "We cannot find the room, please check if the room link is valid."

### ISSUE THREAD

**Issue by AmosChenYQ** [bestony/neshouse#26]
![image](https://user-images.githubusercontent.com/31386769/107125932-a29f1200-68e7-11eb-87bc-20542bc6c3ad.png)

作为admin进入新创建的房间的时候，会遇到这种情况，打log发现是https://github.com/bestony/neshouse/blob/master/js/app.js#L448 这里抛的异常

**Comment by AmosChenYQ** [comment]
去leancloud后台查了一下，三个参数都是正确的，分别是AGORAAPPID、leancloud的Room的 objectId、_user的objectId

**Comment by AmosChenYQ** [comment]
https://docs.agora.io/en/Agora%20Platform/faq/token_error
![image](https://user-images.githubusercontent.com/31386769/107126677-2ce97500-68ec-11eb-9e58-e8246fb50afb.png)
文档确实是调试模式不使用token，并且代码似乎也是这么做的，并且agora那边也是这么设置的：
![image](https://user-images.githubusercontent.com/31386769/107126715-5a362300-68ec-11eb-8424-1af0d8a78eb9.png)

**Comment by johnpoint** [comment]
> 去leancloud后台查了一下，三个参数都是正确的，分别是AGORAAPPID、leancloud的Room的 objectId、_user的objectId

请确认两个地方
1. 所使用项目配置 **安全** - **App** - **主要证书** 为未启用
2. 确认配置文件内 AGORAAPPID 与声网项目的 app id 相吻合

**Comment by bestony** [comment]
这种问题主要是你使用了代理服务器的原因，关掉试试。

Bai HuanCheng（白宦成）
2021年2月7日 +0800 01:58 AmosChenYQ <notifications@github.com>，写道：

**Comment by AmosChenYQ** [comment]
> 这种问题主要是你使用了代理服务器的原因，关掉试试。 Bai HuanCheng（白宦成） 2021年2月7日 +0800 01:58 AmosChenYQ <notifications@github.com>，写道：
> […](#)
> 作为admin进入新创建的房间的时候，会遇到这种情况，打log发现是https://github.com/bestony/neshouse/blob/master/js/app.js#L448 这里抛的异常 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

将代理关闭以后还是会出现相同的问题。

**Comment by bestony** [comment]
你的本地网络环境是什么样的？我联系声网的同学看一下。

Bai HuanCheng（白宦成）

2021年2月7日 +0800 11:35 AmosChenYQ <notifications@github.com>，写道：

**Comment by AmosChenYQ** [comment]
现在是用[vscode live server plugin]( https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) 部署到localhost的 笔记本电脑网络是移动的wifi，新建agora项目的时候用过它自带的那个测试链接测试过可以用

**Comment by AmosChenYQ** [comment]
我直接加您微信私聊吧

**Comment by junbaor** [comment]
遇到了同样的问题。

**Comment by johnpoint** [comment]
> 现在是用[vscode live server plugin](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) 部署到localhost的 笔记本电脑网络是移动的wifi，新建agora项目的时候用过它自带的那个测试链接测试过可以用

我这边使用这个插件进行测试并不能复现您的问题，能不能给下声网那边的项目配置截图？

**Comment by AmosChenYQ** [comment]
> > 现在是用[vscode live server plugin](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) 部署到localhost的 笔记本电脑网络是移动的wifi，新建agora项目的时候用过它自带的那个测试链接测试过可以用
> 
> 我这边使用这个插件进行测试并不能复现您的问题，能不能给下声网那边的项目配置截图？

Agora:
![image](https://user-images.githubusercontent.com/31386769/107149748-63c79580-6995-11eb-8725-062457ebae4c.png)
![image](https://user-images.githubusercontent.com/31386769/107149779-92de0700-6995-11eb-9a08-0338e45f1cea.png)

**Comment by AmosChenYQ** [comment]
leancloud：
![image](https://user-images.githubusercontent.com/31386769/107150045-d2f1b980-6996-11eb-9bc6-da6a651b0120.png)
![image](https://user-images.githubusercontent.com/31386769/107150049-db49f480-6996-11eb-8c86-8556d42854b8.png)

**Comment by johnpoint** [comment]
![image](https://user-images.githubusercontent.com/24842848/107150188-907cac80-6997-11eb-93a3-2d2cf43e42b5.png)
您的项目配置问题，建议你新建一个项目

**Comment by AmosChenYQ** [comment]
OK 我去試試

**Comment by AmosChenYQ** [comment]
新建项目解决了，应该是昨天测试agora的时候把token新加上去了，新建的原始项目是可以的。谢谢。
