### ISSUE TITLE
建议有个讨论的房间

### ISSUE THREAD

**Issue by xushuhui** [bestony/neshouse#29]
今天下午六点多开的一个讨论项目bug的房间已经关了吗，链接：https://neshouse.com/?invite=601fb95447452a1756cb0e47，已经打不开了。本来还想多聊聊，建议有个讨论的房间

**Comment by johnpoint** [comment]
已经关闭了

**Comment by xushuhui** [comment]
什么时候再开个，想加入

**Comment by johnpoint** [comment]
可能不定时会开，但是语音聊天并不算是一个很好的 Bug 反馈渠道，还是更加建议使用 issue 或者其他文字交流渠道汇报 bug。
