### ISSUE TITLE
房间信息有误，请确认后重新加入！

### ISSUE THREAD

**Issue by sumerzhang** [bestony/neshouse#3]
![image](https://user-images.githubusercontent.com/37577949/106880349-34a3f080-6717-11eb-94c2-61036f8d9586.png)
如题，房间信息有误，管理员进不了房间，观众可以进去

**Comment by johnpoint** [comment]
能否提供更多信息？比如是自行部署的还是用的demo

**Comment by sumerzhang** [comment]
使用的demo的，https://neshouse.com/admin.html

之前看控制台，好像是有个请求的api返回的结果是unauthorized。

具体详细结果现在不能复现了，网页改版了。

**Comment by johnpoint** [comment]
那估计已经修复了，我 close 了
