### ISSUE TITLE
小程序版本和其他

### ISSUE THREAD

**Issue by xushuhui** [bestony/neshouse#34]
1. 可以出个小程序版本，更加贴合国内需求
2. 增加头像上传功能，比昵称更具有辨识度
3. 提示弹窗的ui可以更友好一些

**Comment by johnpoint** [comment]
1. 暂时不会考虑
2. 因为目前账号系统的部分并不是传统的结构，所以头像问题可能并不是太好解决，这个建议记录下来了，看看能否实现
3. 在改进中了
