### ISSUE TITLE
Clicking "Allow" in the Speaker's Waiting Bench does not add a speaker

### ISSUE THREAD

**Issue by farahbrunache** [bestony/neshouse#35]
As the admin, I correctly see a person in the "Speaker's Waiting Bench." But when I click "Allow" nothing happens. I tried this in Chrome and Firefox. This is the error I get:

![image](https://user-images.githubusercontent.com/16567092/107179981-a8026800-698c-11eb-9416-d9c44aab6b34.png)

**Comment by johnpoint** [comment]
Please check the permission settings of leancloud to ensure that all users can read and write
![Screenshot_20210208-145923__01](https://user-images.githubusercontent.com/24842848/107186035-7d60ef80-6a1e-11eb-9abe-d7076d3f8f9d.jpg)

**Comment by farahbrunache** [comment]
@johnpoint you're the best! Problem solved.
