### ISSUE TITLE
Can't create a house because can't find "Log in to chat room as Administrator"

### ISSUE THREAD

**Issue by HackYardo** [bestony/neshouse#39]

**Comment by johnpoint** [comment]
We need more information from you to help you solve this problem.

**Comment by HackYardo** [comment]
After I enter the room name and user name in https://neshouse.com/admin.html, I can't find "log in..." below?

**Comment by bestony** [comment]
Due to security reasons, the online version's room creation feature is blocked and you will need to deploy this version yourself. If you just want to try it out, you can contact `ixiqin_com` on WeChat to get a link to the test room
